ProyectoTienda/proyecto_tienda/ofertas/urls.py
from django.urls import path
from . import views
 
app_name='ofertas'
 
urlpatterns = [
    path('', views.index, name='index'),
    path('crear_oferta/', views.crear_oferta, name='crear_oferta'),  # Agregar esta línea
    path('eliminar_oferta/<int:oferta_id>/', views.eliminar_oferta, name='eliminar_oferta'),
    path('editar_oferta/<int:oferta_id>/', views.editar_oferta, name='editar_oferta'),
]

ProyectoTienda/proyecto_tienda/productos/urls.py
from django.urls import path
from . import views

app_name='productos'

urlpatterns= [
    path('', views.index, name='index'),
]

ProyectoTienda/proyecto_tienda/proyecto_tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include ('productos.urls')),
    path('ofertas/', include('ofertas.urls')),
    path('', views.index, name='index'),
    path('account/login/', auth_views.LoginView.as_view(), 'login'),
]

ProyectoTienda/proyecto_tienda/ofertas/models.py
from django.db import models
from django.forms import ValidationError
from productos.models import Producto

# Create your models here.


class Oferta(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    porcentaje_descuento = models.DecimalField(max_digits=6, decimal_places=2)
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()

    def clean(self):  # metodo especial para validaciones personalizadas
        if self.fecha_inicio >= self.fecha_fin:
            raise ValidationError(
                'La fecha de inicio debe ser menor que la fecha de fin')
        if self.porcentaje_descuento < 0 or self.porcentaje_descuento > 100:
            raise ValidationError(
                'El porcentaje de descuento debe estar entre 0 y 100')

    def save(self, *args, **kwargs):  # invoca a Clean antes de guardar los datos
        self.clean()
        super(Oferta, self).save(*args, **kwargs)

    def __str__(self):
        return f" oferta en: {self.producto} --- Descuento: {self.porcentaje_descuento} %"

    @property
    def precio_descuento(self):
        precioDescuento = self.producto.precio - \
            (self.producto.precio * self.porcentaje_descuento / 100)
        return round(precioDescuento, 2)

    # definimos una clase meta para definir los permisos del modelo
    class Meta:
        permissions = [
            ('ver_ofertas', 'ver ofertas'),
            ('crear_ofertas', 'crear ofertas'),
            ('editar_ofertas', 'editar ofertas'),
            ('eliminar_ofertas', 'eliminar ofertas')
        ]

ProyectoTienda/proyecto_tienda/productos/models.py
from django.db import models

# Create your models here.       #acá creamos las tablas Categoría y Producto
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre
    

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    categoria =  models.ForeignKey (Categoria, on_delete=models.CASCADE)      
    
    def __str__(self):
        return self.nombre
    
    

ProyectoTienda/proyecto_tienda/ofertas/forms.py
from django import forms
from .models import Oferta

class OfertaForm(forms.ModelForm):
    fecha_inicio = forms.DateTimeField(widget=forms.DateTimeInput(attrs=
    {'type':'datetime-local'}), input_formats=['%d-%m-%Y T%H:%M'])
    fecha_fin = forms.DateTimeField(widget=forms.DateTimeInput(attrs=
    {'type':'datetime-local'}), input_formats=['%d-%m-%Y T%H:%M'])

    class Meta:
        model=Oferta
        fields=['producto', 'porcentaje_descuento', 'fecha_inicio', 'fecha_fin']

ProyectoTienda/proyecto_tienda/ofertas/views.py
from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404
from .models import Oferta
from .forms import OfertaForm
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.

@login_required()
@permission_required('ofertas.editar_oferta', raise_exception=True)
def editar_oferta(request, oferta_id):
    oferta = get_object_or_404(Oferta, id=oferta_id)
    if request.method == 'POST':
        form = OfertaForm(request.POST, instance=oferta)
        if form.is_valid():
            form.save()
            return redirect('ofertas:index')
    else:
        form = OfertaForm(instance=oferta)
    return render(request, 'ofertas/crear_oferta.html', {'form': form})

@permission_required('ofertas.eliminar_oferta', raise_exception=True)
def eliminar_oferta(request, oferta_id):
    oferta = get_object_or_404(Oferta, id=oferta_id)
    if request.method == 'POST':
        oferta.delete()
        return redirect('ofertas: index')
    return render(request, 'ofertas/eliminar_oferta.html', {'oferta': oferta})

@permission_required('oferta.crear_oferta', raise_exception=True)
def crear_oferta(request):
    if request.method == 'POST':
        form = OfertaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ofertas:index')
    else:
        form = OfertaForm
    return render(request, 'ofertas/crear_oferta.html', {'form': form})

def index(request):
    current_date = datetime.now()
    ofertas = []

    try:
        ofertas = Oferta.objects.filter(fecha_inicio__lte=current_date,
                                        fecha_fin__gte=current_date)
        # raise Exception("no hay ofertas disponibles en este momento")
        if not ofertas:
            raise ValueError("no hay ofertas disponibles en este momento")
    except ValueError as e:
        # manejo de error especifico
        return render(request, 'ofertas/index.html', {'error': str(e),
                                                      'current_date': current_date})
    except Exception as e:
        # Manejo de cualquier otro error
        return render(request, 'ofertas/index.html',
                      {'error': 'Se produjo  un error inesperado!', 'current_date': current_date})
    context = {
        'current_date': current_date,
        # is_special_offer: False #false para no y true para si
        'ofertas': ofertas
    }
    return render(request, 'ofertas/index.html', context)

ProyectoTienda/proyecto_tienda/productos/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.
def index(request):
    productos = Producto.objects.all()
    return render(request, 'productos/index.html', {'productos': productos})

ProyectoTienda/proyecto_tienda/proyecto_tienda/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')#renderiza la plantilla index.html

ProyectoTienda/proyecto_tienda/ofertas/templates/ofertas/crear_oferta.html
{% extends 'base.html'%}
{% block title%}Crear Oferta{%endblock%}
{% block content%}

<h1>Crear Nueva Oferta</h1>
<form method="post">
    {% csrf_token %}   <!--Token para proteger de ataques CSRF-->
    {{ form.as_p }}    <!--metodo para renderizar el formulario mostrando los campos como parrafo-->
    <button type="submit">Crear Oferta</button>


</form>


{%endblock%} 

ProyectoTienda/proyecto_tienda/ofertas/templates/ofertas/eliminar_oferta.html
{% extends 'base.html'%}
{% block title%}Eliminar Oferta{%endblock%}
{% block content%}

<h1>Eliminar Oferta</h1>
<h4>¿Esta seguro de eliminar la oferta para el producto <strong>{{oferta.producto.nombre}}</strong> ?</h4>
<form metho="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Confirmar</button>
</form>

<a href="{% url 'ofertas:index' %}"> Cancelar</a>

{%endblock%}

ProyectoTienda/proyecto_tienda/ofertas/templates/ofertas/index.html
{% extends 'base.html' %}
{% block title %} OFERTAS {% endblock %}
{% block content %} 
{% load static %}

    <div style="text-align: center;">
        <h1>Bienvenidos a la sección de Ofertas</h1>
        <p>Fecha de hoy: {{current_date|date:"d-m-Y"}}</p>
        {% if error%}
        <div class="alert alert-danger"> {{error}}</div>
        {% endif %}

    </div>

    <div>
        <h3>Aquí puedes ver la lista de ofertas</h3>
        <!--<p>¿Hay oferta especial Hoy?: {{is_special_offert|yesno:'Si,No'}}</p>
    -->
        {% if ofertas %}
            <h2>Productos en Oferta!!</h2>
            <ol>
                {% for oferta in ofertas %}
                    <li>{{oferta.producto.nombre}} - Precio Original: ${{oferta.producto.precio}} - Precio Con Descuento: ${{oferta.precio_descuento}}
                        Descuento: {{oferta.porcentaje_descuento}}%
                    </li>
                {% endfor %}
                
            </ol>
        {% else %}
            <p><img src="{% static 'img/ofertas.jpg' %}"></p>
            
        {% endif %}

    </div>
    <br>
    <br>

    <div>
        <h4>Aquí puedes navegar a las otras app o regresar al inicio</h4>
        
        <a href="{% url 'productos:index'  %}">Ir a Productos</a>
        <br>
        <a href="{% url 'index' %}">Ir a la pagina Principal</a>
    </div>
{% endblock %}

ProyectoTienda/proyecto_tienda/productos/templates/productos/index.html
{% extends 'base.html' %}
{% block title %} PRODUCTOS {% endblock %}
{% block content %} 

    <div>
        <h1>Bienvenidos a la sección de Productos</h1>
    </div>
    <div>
        <h4>Aquí puedes navegar a las otras app o regresar al inicio</h4>
        
        <a href="{% url 'ofertas:index'  %}">Ir a ofertas</a>
        <br>
        <a href="{% url 'index' %}">Ir a la pagina Principal</a>
    </div>

    <div>
        <h2> Listado de Productos</h2>
        
        <div class="container">
            <table>
                <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Precio</th>
                        <th>Categoría</th>
                    </tr>
                </thead>
                <tbody>
                    {% for producto in productos %}
                    <tr>
                        <td>{{ producto.nombre }}</td>
                        <td>{{ producto.precio }}</td>
                        <td>{{ producto.categoria.nombre }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3">
                            <h5>No hay productos disponibles</h5>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
    </div>

{% endblock %}

ProyectoTienda/proyecto_tienda/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} PAGINA PRINCIPAL {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Mi Tienda</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
                data-bs-target="#navbarNav" aria-controls="navbarNav" 
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'productos:index'  %}">Ir a Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ofertas:index' %}">Ir a Ofertas</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Contenido Principal -->
    <div class="container mt-4">
        {% block content %} {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

ProyectoTienda/proyecto_tienda/templates/index.html
{% extends 'base.html' %}

{% block title %} PAGINA PRINCIPAL {% endblock %}

{% block content %} 
   <header class="text-center">
        <h1>PAGINA PRINCIPAL</h1>
   </header>

   <div class="jumbotron bg-light p-5 rounded mt-4">
        <div class="row">
            <div class="col-lg-8 col-md-10 col-sm-12 mx-auto text-center">
                <h2 class="display-4">Bienvenido a Nuestra Tienda</h2>
                <p class="lead">Explora nuestra selección de productos y ofertas</p>
                <hr class="my-4">
                <p>Haz clic en los enlaces de arriba para ir a nuestras categorías</p>
                <button id="show-alert" class="btn btn-warning btn-lg btn-block">Presiona Aquí</button>
            </div>
        </div>
   </div>

   <nav class="text-center">
        <a class="btn btn-primary" href="{% url 'productos:index'%}">Ir a Productos</a>
        <a class="btn btn-secondary" href="{% url 'ofertas:index'%}">Ir a Ofertas</a>
   </nav>

{% endblock %}